"use client";

import { getTier, totalItems, levels } from "@/data/checklist";

interface Props {
  checkedItems: Set<string>;
}

export function ExportButton({ checkedItems }: Props) {
  const generateReport = () => {
    const score = checkedItems.size;
    const percentage = Math.round((score / totalItems) * 100);
    const tier = getTier(score);

    const levelReports = levels.map((level) => {
      const checked = level.items.filter((item) => checkedItems.has(item.id));
      const unchecked = level.items.filter((item) => !checkedItems.has(item.id));
      return {
        name: level.name,
        checked: checked.length,
        total: level.items.length,
        checkedItems: checked,
        uncheckedItems: unchecked,
      };
    });

    const report = `# Agent-Readiness Audit Report

## Overall Score: ${score}/${totalItems} (${percentage}%)

**Tier:** ${tier.emoji} ${tier.name}
> ${tier.description}

---

${levelReports
  .map(
    (lr) => `## Level: ${lr.name} (${lr.checked}/${lr.total})

### Completed ✅
${lr.checkedItems.length > 0 ? lr.checkedItems.map((item) => `- [x] ${item.id} ${item.title}`).join("\n") : "- None yet"}

### Todo ❌
${lr.uncheckedItems.length > 0 ? lr.uncheckedItems.map((item) => `- [ ] ${item.id} ${item.title}`).join("\n") : "- All complete!"}`
  )
  .join("\n\n---\n\n")}

---

*Generated by [Agent-Readiness Audit](https://github.com/joeyjanisheck/agent-readiness-audit)*
`;

    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "agent-readiness-audit.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyShareLink = () => {
    const checked = Array.from(checkedItems).sort().join(",");
    const url = new URL(window.location.href);
    url.searchParams.set("c", checked);
    navigator.clipboard.writeText(url.toString());
    alert("Share link copied to clipboard!");
  };

  return (
    <div className="flex gap-2">
      <button
        onClick={generateReport}
        className="flex-1 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 border border-zinc-600 rounded-lg text-sm font-medium text-zinc-200 transition-colors"
      >
        📄 Export Report
      </button>
      <button
        onClick={copyShareLink}
        className="flex-1 px-4 py-2 bg-green-600 hover:bg-green-500 rounded-lg text-sm font-medium text-white transition-colors"
      >
        🔗 Share Link
      </button>
    </div>
  );
}
